import { useState } from "react";
import { supabase } from "../lib/supabaseClient";
import "./AddProduct.css";

const INITIAL_FORM_STATE = {
  barcode: "",
  name: "",
  pack: "",
  batch: "",
  price: "",
  stockQuantity: "",
  quantity: "",
  gst: "",
  expiryDate: "",
};

function AddProduct() {
  const [formData, setFormData] = useState(INITIAL_FORM_STATE);
  const [existingProductId, setExistingProductId] = useState(null);
  const [loading, setLoading] = useState(false);

  function handleChange(e) {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
  }

  // BARCODE LOOKUP — checks if product exists
  async function handleBarcodeCheck() {
    const barcode = formData.barcode.trim();
    if (!barcode) return;

    try {
      const { data, error } = await supabase
        .from("items")
        .select("*")
        .eq("barcode", barcode)
        .limit(1);

      if (error) throw error;

      if (data && data.length > 0) {
        const item = data[0];
        setExistingProductId(item.id);

        setFormData({
          barcode: item.barcode || "",
          name: item.name || "",
          pack: item.pack || "",
          batch: item.batch || "",
          price: item.price ?? "",
          stockQuantity:
            item.stock_quantity !== null && item.stock_quantity !== undefined
              ? Number(item.stock_quantity) + 1
              : 1,
          quantity: item.quantity ?? "",
          gst: item.gst ?? "",
          expiryDate: item.expiry_date || "",
        });

        alert(`Existing product found: ${item.name}`);
      } else {
        setExistingProductId(null);
        setFormData({ ...INITIAL_FORM_STATE, barcode });
      }
    } catch (error) {
      console.error("Barcode lookup failed:", error.message);
    }
  }

  // SUBMIT — insert new or update existing
  async function handleSubmit(e) {
    e.preventDefault();
    setLoading(true);

    const payload = {
      barcode: formData.barcode,
      name: formData.name,
      pack: formData.pack || null,
      batch: formData.batch || null,
      price: formData.price === "" ? null : Number(formData.price),
      stock_quantity:
        formData.stockQuantity === "" ? 0 : Number(formData.stockQuantity),
      quantity: formData.quantity === "" ? null : Number(formData.quantity),
      gst: formData.gst === "" ? null : Number(formData.gst),
      expiry_date: formData.expiryDate || null,
    };

    try {
      let error;

      if (existingProductId) {
        // UPDATE existing row
        const { error: updateError } = await supabase
          .from("items")
          .update(payload)
          .eq("id", existingProductId);
        error = updateError;
      } else {
        // INSERT new row (id is auto-generated by Supabase since it's int8 identity)
        const { error: insertError } = await supabase
          .from("items")
          .insert([payload]);
        error = insertError;
      }

      if (error) throw error;

      alert(
        existingProductId
          ? "Inventory updated successfully!"
          : "New product added successfully!"
      );

      setFormData(INITIAL_FORM_STATE);
      setExistingProductId(null);
    } catch (error) {
      console.error("Save failed:", error.message);
      alert(`Failed to save product: ${error.message}`);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="add-product-page">
      <div className="add-product-container">
        <h1 className="add-product-title">
          {existingProductId ? "Update Existing" : "Add New"} Product
        </h1>

        <form className="product-form" onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Barcode</label>
            <input
              type="text"
              name="barcode"
              value={formData.barcode}
              onChange={handleChange}
              onBlur={handleBarcodeCheck}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  e.preventDefault();
                  handleBarcodeCheck();
                }
              }}
              placeholder="Type barcode and press Enter"
              required
            />
          </div>

          <div className="form-group">
            <label>Product Name</label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
            />
          </div>

          <div className="form-group">
            <label>Pack</label>
            <input
              type="text"
              name="pack"
              value={formData.pack}
              onChange={handleChange}
              placeholder="e.g., 10 tablets"
            />
          </div>

          <div className="form-group">
            <label>Batch</label>
            <input
              type="text"
              name="batch"
              value={formData.batch}
              onChange={handleChange}
              placeholder="Batch number"
            />
          </div>

          <div className="form-group">
            <label>Price (₹)</label>
            <input
              type="number"
              step="0.01"
              name="price"
              value={formData.price}
              onChange={handleChange}
              required
            />
          </div>

          <div className="form-group">
            <label>Stock Quantity</label>
            <input
              type="number"
              name="stockQuantity"
              value={formData.stockQuantity}
              onChange={handleChange}
              required
            />
          </div>

          <div className="form-group">
            <label>Quantity (per pack)</label>
            <input
              type="number"
              name="quantity"
              value={formData.quantity}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label>GST (%)</label>
            <input
              type="number"
              step="0.01"
              name="gst"
              value={formData.gst}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label>Expiry Date</label>
            <input
              type="date"
              name="expiryDate"
              value={formData.expiryDate}
              onChange={handleChange}
            />
          </div>

          <button type="submit" className="submit-btn" disabled={loading}>
            {loading
              ? "Saving..."
              : existingProductId
              ? "Update Inventory Stock"
              : "Add New Product"}
          </button>
        </form>
      </div>
    </div>
  );
}

export default AddProduct;